
version: "3.9"
services:
  web:
    build: .
    command: python /audit_tool/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/audit_tool
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-g=c%p2bpz!#x!o62o9@0nr&*55lzhq3$$23k=5#nz$$t(c)0k@=v"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: